#!/usr/bin/env npx ts-node --project scripts/fix-cves/tsconfig.json

/**
 * Generate Jira-ready cve-report.md, PR body, and GitHub Job Summary.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { FixRunResults, PackageFixResult } from './types';
import { getArg, readJson, writeFile } from './utils';

function verificationLabel(pkg: PackageFixResult): string {
  if (pkg.verified === true) return 'PASS';
  if (pkg.verified === false) return 'FAIL';
  return 'NOT RUN';
}

function buildJiraReport(results: FixRunResults): string {
  const lines: string[] = [];
  lines.push(`h2. CVE Remediation Report — ${results.jiraId}`);
  lines.push('');
  lines.push(`*Release branch:* {{${results.releaseBranch || 'n/a'}}}`);
  if (results.prUrl) {
    lines.push(`*Pull Request:* [${results.prUrl}|${results.prUrl}]`);
  }
  lines.push('');
  lines.push('||Package||Strategy||Fixed Version(s)||Verification||');
  for (const pkg of results.packages) {
    lines.push(
      `|{{${pkg.package}}}|${pkg.strategy}|${pkg.fixedVersions.join(
        ', ',
      )}|${verificationLabel(pkg)}|`,
    );
  }
  lines.push('');

  for (const pkg of results.packages) {
    lines.push(`h3. ${pkg.package}`);
    lines.push('');
    lines.push(`* Strategy: {{${pkg.strategy}}}`);
    lines.push(`* Fixed version(s): {{${pkg.fixedVersions.join(', ')}}}`);
    lines.push(`* Applied action: ${pkg.appliedAction}`);
    lines.push(`* Analysis reason: ${pkg.reason}`);
    lines.push(
      `* Verification: *${verificationLabel(pkg)}* — ${
        pkg.verificationDetail || 'n/a'
      }`,
    );
    lines.push('');
  }

  const triage = results.packages.filter((p) => p.strategy === 'triage-needed');
  if (triage.length) {
    lines.push('h3. Triage Required');
    lines.push('');
    lines.push(
      'The following packages could not be automatically remediated and need manual follow-up:',
    );
    lines.push('');
    for (const pkg of triage) {
      lines.push(`* {{${pkg.package}}} — ${pkg.reason}`);
    }
    lines.push('');
  }

  lines.push('----');
  lines.push('_Generated by the fix-cves GitHub Actions workflow._');
  lines.push('');
  return lines.join('\n');
}

function buildMarkdownReport(results: FixRunResults): string {
  const lines: string[] = [];
  lines.push(`# CVE Remediation Report — ${results.jiraId}`);
  lines.push('');
  lines.push(`**Release branch:** \`${results.releaseBranch || 'n/a'}\``);
  if (results.prUrl) {
    lines.push(`**Pull Request:** ${results.prUrl}`);
  }
  lines.push('');
  lines.push('| Package | Strategy | Fixed Version(s) | Verification |');
  lines.push('| --- | --- | --- | --- |');
  for (const pkg of results.packages) {
    lines.push(
      `| \`${pkg.package}\` | ${pkg.strategy} | ${pkg.fixedVersions.join(
        ', ',
      )} | ${verificationLabel(pkg)} |`,
    );
  }
  lines.push('');

  for (const pkg of results.packages) {
    lines.push(`## ${pkg.package}`);
    lines.push('');
    lines.push(`- **Strategy:** \`${pkg.strategy}\``);
    lines.push(`- **Fixed version(s):** \`${pkg.fixedVersions.join(', ')}\``);
    lines.push(`- **Applied action:** ${pkg.appliedAction}`);
    lines.push(`- **Analysis reason:** ${pkg.reason}`);
    lines.push(
      `- **Verification:** **${verificationLabel(pkg)}** — ${
        pkg.verificationDetail || 'n/a'
      }`,
    );
    lines.push('');
  }

  const triage = results.packages.filter((p) => p.strategy === 'triage-needed');
  if (triage.length) {
    lines.push('## Triage Required');
    lines.push('');
    lines.push(
      'The following packages could not be automatically remediated and need manual follow-up:',
    );
    lines.push('');
    for (const pkg of triage) {
      lines.push(`- \`${pkg.package}\` — ${pkg.reason}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by the fix-cves GitHub Actions workflow._');
  lines.push('');
  return lines.join('\n');
}

function validationLabel(passed: boolean | null | undefined): string {
  if (passed === true) return 'PASS';
  if (passed === false) return 'FAIL';
  return 'NOT RUN';
}

function buildPrBody(results: FixRunResults): string {
  const lines: string[] = [];
  lines.push('## Type of Change');
  lines.push('');
  lines.push('- [x] CVE Fix');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  const label = results.jiraId ? `**${results.jiraId}**` : 'CVE remediation';
  lines.push(`Automated ${label} on \`${results.releaseBranch}\`.`);
  lines.push('');
  lines.push('## Packages Fixed');
  lines.push('');
  lines.push('| Package | Strategy | Fixed Version(s) | Verification |');
  lines.push('| --- | --- | --- | --- |');
  for (const pkg of results.packages) {
    lines.push(
      `| \`${pkg.package}\` | ${pkg.strategy} | ${pkg.fixedVersions.join(
        ', ',
      )} | ${verificationLabel(pkg)} |`,
    );
  }
  lines.push('');

  lines.push('## Validation');
  lines.push('');
  lines.push('| Check | Result |');
  lines.push('| --- | --- |');
  lines.push(`| yarn build | ${validationLabel(results.buildPassed)} |`);
  lines.push(`| yarn test | ${validationLabel(results.testPassed)} |`);
  lines.push('');

  for (const pkg of results.packages) {
    lines.push(`## \`${pkg.package}\``);
    lines.push('');
    lines.push(`- **Strategy:** \`${pkg.strategy}\``);
    lines.push(`- **Action:** ${pkg.appliedAction}`);
    lines.push(`- **Reason:** ${pkg.reason}`);
    lines.push(
      `- **Verification:** **${verificationLabel(pkg)}** — ${
        pkg.verificationDetail || 'n/a'
      }`,
    );
    lines.push('');

    if (pkg.yarnWhyRaw || pkg.npmLsRaw) {
      lines.push('<details>');
      lines.push(`<summary>Before fix: yarn why / npm ls</summary>`);
      lines.push('');
      if (pkg.yarnWhyRaw) {
        lines.push('**yarn why:**');
        lines.push('```');
        lines.push(pkg.yarnWhyRaw);
        lines.push('```');
      }
      if (pkg.npmLsRaw) {
        lines.push('**npm ls --all:**');
        lines.push('```');
        lines.push(pkg.npmLsRaw);
        lines.push('```');
      }
      lines.push('</details>');
      lines.push('');
    }

    if (pkg.verifyYarnWhy || pkg.verifyNpmLs) {
      lines.push('<details>');
      lines.push(`<summary>After fix: yarn why / npm ls</summary>`);
      lines.push('');
      if (pkg.verifyYarnWhy) {
        lines.push('**yarn why:**');
        lines.push('```');
        lines.push(pkg.verifyYarnWhy);
        lines.push('```');
      }
      if (pkg.verifyNpmLs) {
        lines.push('**npm ls --all:**');
        lines.push('```');
        lines.push(pkg.verifyNpmLs);
        lines.push('```');
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_Generated by the fix-cves GitHub Actions workflow._');
  lines.push('');
  return lines.join('\n');
}

function buildJobSummary(results: FixRunResults): string {
  const lines: string[] = [];
  lines.push(`## CVE Fix Summary — ${results.jiraId}`);
  lines.push('');
  if (results.prUrl) {
    lines.push(`**PR:** ${results.prUrl}`);
    lines.push('');
  }
  lines.push(`**Branch:** \`${results.releaseBranch}\``);
  lines.push('');
  lines.push('| Package | Strategy | Verification |');
  lines.push('| --- | --- | --- |');
  for (const pkg of results.packages) {
    lines.push(
      `| \`${pkg.package}\` | ${pkg.strategy} | ${verificationLabel(pkg)} |`,
    );
  }
  lines.push('');
  const overall =
    results.triageNeeded || results.verificationFailed ? 'FAILED' : 'PASSED';
  lines.push(`**Overall status:** ${overall}`);
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const artifactsDir = getArg('--artifacts-dir') ?? 'cve-artifacts';
  const resultsPath =
    getArg('--results') ?? path.join(artifactsDir, 'results.json');
  const prUrl = getArg('--pr-url');
  const format = getArg('--format') ?? 'markdown'; // markdown | jira

  const results = readJson<FixRunResults>(resultsPath);
  if (prUrl) {
    results.prUrl = prUrl;
    writeFile(resultsPath, JSON.stringify(results, null, 2) + '\n');
  }

  // Always generate both
  const mdReport = buildMarkdownReport(results);
  writeFile(path.join(artifactsDir, 'cve-report.md'), mdReport);

  const jiraReport = buildJiraReport(results);
  writeFile(path.join(artifactsDir, 'cve-report-jira.md'), jiraReport);

  const prBodyPath = path.join(artifactsDir, 'pr-body.md');
  writeFile(prBodyPath, buildPrBody(results));

  const summary = buildJobSummary(results);
  writeFile(path.join(artifactsDir, 'job-summary.md'), summary);

  const writeSummary = process.argv.includes('--write-summary');
  const stepSummary = process.env.GITHUB_STEP_SUMMARY;
  if (writeSummary && stepSummary) {
    fs.appendFileSync(stepSummary, summary);
  }

  console.log(`Wrote ${path.join(artifactsDir, 'cve-report.md')}`);
  console.log(`Wrote ${path.join(artifactsDir, 'cve-report-jira.md')}`);
  console.log(`Wrote ${prBodyPath}`);
}

main();
