---
plugin:
  name: ''
  description: ''
  image: ''
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ''
  serviceAccount:
    create: true
    annotations: {}
    name: ''
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ''
  jobs:
    patchConsoles:
      enabled: true
      image: 'registry.redhat.io/openshift4/ose-tools-rhel8@sha256:4c7b1ede6b311641e58df25d82f40d4eca997de7a5c4e8279d57ce8a9cd07ddb'
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
