---
plugin:
  name: ''
  description: ''
  image: ''
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ''
  serviceAccount:
    create: true
    annotations: {}
    name: ''
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ''
  jobs:
    patchConsoles:
      enabled: true
      image: 'registry.redhat.io/openshift4/ose-tools-rhel8@sha256:210d3b59f2abed3a18558f9dd95391f59c5a6c653ca6c75b861d1c754e7f790a'
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
