export const pageTitle = {
  Git: 'Import from Git',
  ContainerImage: 'Deploy Image',
  YAML: 'Import YAML',
  DeveloperCatalog: 'Developer Catalog',
  Pipelines: 'Pipelines',
  PipelineBuilder: 'Pipeline builder',
  Add: 'Add',
  Search: 'Search',
  PipelineRunDetails: 'PipelineRun details',
  PipelineDetails: 'Pipeline details',
  TriggerTemplateDetails: 'TriggerTemplate details',
  EventListenerDetails: 'EventListener details',
  ClusterTriggerTemplateDetails: 'ClusterTriggerBinding details',
  Templates: 'Templates',
  BuilderImages: 'Builder Images',
  OperatorHub: 'OperatorHub',
  InstallOperator: 'Install Operator',
  InstalledOperators: 'Installed Operators',
  Environments: 'Environments',
  PipelineRuns: 'PipelineRuns',
  CreateKnativeServing: 'Create KnativeServing',
  CreateKnativeEventing: 'Create KnativeEventing',
  CreateKnativeKafka: 'Create KnativeKafka',
  KnativeServings: 'KnativeServings',
  KnativeEventings: 'KnativeEventings',
  KnativeKafka: 'KnativeKafkas',
  CreateRepository: 'Create Repository',
  CustomResourceDefinitions: 'CustomResourceDefinitions',
  AddGitRepository: 'Add Git Repository',
};
