nodeLinker: node-modules

supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
    - arm64
    - s390x
    - ppc64

# Force packages to use the same webpack instance
packageExtensions:
  "@openshift-console/dynamic-plugin-sdk-webpack@*":
    peerDependencies:
      webpack: "*"