# .yarnrc.yml
nodeLinker: node-modules

# Let Corepack fetch Yarn automatically
# No local binary committed to the repo
enableImmutableInstalls: true

# Force packages to use the same webpack instance
packageExtensions:
  "@openshift-console/dynamic-plugin-sdk-webpack@*":
    peerDependencies:
      webpack: "*"
