# Yarn 4.6 configuration
nodeLinker: node-modules

# Use the bundled yarn release for offline/hermetic builds
yarnPath: .yarn/releases/yarn-4.6.0.cjs

# Enable compression for yarn cache
compressionLevel: mixed

# Telemetry opt-out
enableTelemetry: false
