codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
        flags:
          - unit-tests
        paths:
          - "src"
        if_ci_failed: error
        informational: false
    patch:
      default:
        target: auto
        threshold: 0%
        flags:
          - unit-tests
        paths:
          - "src"

flags:
  unit-tests:
    carryforward: true

ignore:
  - 'src/test-data/**'
  - 'src/types/**'
  - '__mocks__/**'
  - 'integration-tests/**'
