FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:18 as build
COPY --from=openshift/origin-cli:latest /usr/bin/oc /usr/local/bin/oc
# Enable corepack for yarn 4.6.0 support
RUN corepack enable
