export const topologyPO = {
  switcher: 'button[data-test-id="topology-switcher-view"]',
  //   noWorkLoadsText: 'h2.co-hint-block__title',
  title: 'h1.ocs-page-layout__title',
  search: '[data-test-id="item-filter"]',
  highlightNode: '.is-filtered',
  // resetView: '[id="reset-view"]',
  //   clearFilter: '[class*="toolbar__item"]',
  //   emptyStateIcon: '[class*= empty-state__icon]',
  //   emptyText: '[data-test="no-resources-found"]',
  //   addToApplication: '[data-test-action="add-to-application"]',
  //   menuItemInContext: 'button[role="menuitem"]',
  //   quickSearch: '[data-test="quick-search-bar"]',
  //   filterByResourceDropDown: '[data-test="filter-by-resource"] button',
  //   topologyDropDown: 'button[aria-label="Options menu"]',
  //   emptyView: {
  //     startBuildingYourApplicationLink:
  //       '[data-test="start-building-your-application"]',
  //     addPageLink: '[data-test="add-page"]',
  //   },
  graph: {
    reset: '#reset-view',
    // layoutViewGroup: '.odc-topology__layout-group',
    // zoomIn: '#zoom-in',
    // zoomOut: '#zoom-out',
    // saveModal: '[data-test="confirm-action"]',
    // modalContent: '[class="modal-content"]',
    fitToScreen: '#fit-to-screen',
    contextMenu: '#popper-container ul',
    workloads: 'g[data-surface="true"]',
    node: '[data-test-id="base-node-handler"]',
    // workload: '[data-type="workload"]',
    // triggerLink: '[data-type="event-pubsub-link"]',
    // triggerEdgeLink: '[data-test-id="edge-handler"] path',
    // confirmModal: '[data-test="confirm-action"]',
    deleteWorkload: '[data-test="confirm-action"]',
    // eventSourceWorkload: '[data-type="event-source"]',
    // applicationGroupingTitle: '.odc-topology-list-view__application-label',
    // addNewAnnotations: '[data-test="add-button"]',
    deleteApplication: '[id="form-input-resourceName-field"]',
    // connector: '[data-test-id="edge-handler"]',
    // routeDecorator: '[aria-label="Open URL"]',
  },
  list: {
    // appName: '#HelmRelease ul li div',
    // nodeName: '#HelmRelease ul li div',
    switcher:
      '[data-test-id="topology-switcher-view"][aria-label="Graph view"]',
    // view: '[aria-label="Topology List View"]',
    // switchGraph: '[aria-label="Graph view"]',
  },
  sidePane: {
    // actionsDropDown: '[data-test-id="actions-menu-button"]',
    // showPodCount: '[id$=show-pod-count]',
    dialog: '[data-test="topology-sidepane"]',
    title: '[role="dialog"] h1',
    // knativeServiceIcon: '[title="Service"]',
    // tabs: '[role="dialog"] li button',
    sectionTitle: 'h2',
    // close: 'button[aria-label="Close"]',
    // labelsList: '[data-test="label-list"]',
    // editAnnotations: '[data-test="edit-annotations"]',
    tabName: '[role="dialog"] li button',
    // healthCheckAlert: 'div.odc-topology-sidebar-alert',
    // resourceQuotaAlert: '[class*=warning]',
    // podScaleUP: '[aria-label="Increase the Pod count"]',
    // podScaleDown: '[aria-label="Decrease the Pod count"]',
    // podText: 'text.pod-ring__center-text',
    // applicationGroupingsTitle: '.overview__sidebar-pane-head.resource-overview__heading',
    // applicationGroupingsSidepane: 'overview__sidebar-pane resource-overview',
    // resourcesTabApplicationGroupings: '.co-m-horizontal-nav__menu-item',
    pipelineRunsDetails: '.sidebar__section-heading',
    pipelineRunsLogSnippet: '.ocs-log-snippet__log-snippet',
    pipelineRunsStatus: '.ocs-log-snippet__status-message',
    pipelineRunsLinks: 'a.sidebar__section-view-all',
    // detailsTab: {
    //   labels: '[data-test="label-list"]',
    //   annotations: '[data-test="edit-annotations"]',
    //   labelsEdit: '[data-test="Labels-details-item__edit-button"]',
    // },
    resourcesTab: {
      startLastRun:
        '[role="dialog"] li.list-group-item.pipeline-overview div button',
      pipelineRuns: 'li.odc-pipeline-run-item',
      //   routeLink: '[data-test-id="route-link"]',
      //   waitingPods: 'button[data-test="waiting-pods"]',
      //   podTrafficStatus: 'div[data-test="pod-traffic-status',
    },
    // monitoringTab: {
    //   viewMonitoringDashBoardsLink: '[data-test="observe-dashboards-link"]',
    // },
    // releaseNotesTab: {},
  },
};
