export const FLAG_HIDE_STATIC_PIPELINE_PLUGIN_PIPELINE_DETAIL_METRICS_TAB =
  'HIDE_STATIC_PIPELINE_PLUGIN_PIPELINE_DETAIL_METRICS_TAB';
export const FLAG_PIPELINE_TEKTON_RESULT_INSTALLED =
  'PIPELINE_TEKTON_RESULT_INSTALLED';
export const ALL_NAMESPACES_KEY = '#ALL_NS#';
